java_library(
    name = "kbcomplete",
    srcs = glob([
        "*.java",
        ]
    ),
    visibility = ["//visibility:public"],
    deps = [
        "@graknlabs_client_java//:client-java",
        "@graknlabs_graql//java:graql",
    ],
)