define

label sub attribute,
    datatype string;

# ===== Properties =====

type-label sub label;

role-label sub label;

var-property sub relation,
    abstract,
    plays body,
    plays head;

isa-property sub var-property,
    relates instance,
    has type-label;

has-attribute-property sub var-property,
    relates owner;

relation-property sub var-property,
    relates roleplayer,
    relates rel,
    has role-label;

# ===== Inference =====

rule-label sub label;

inference sub relation,
    relates body,
    relates head,
    has rule-label;
