java_library(
    name = "kbtest",
    srcs = glob([
        "*.java",
        ]
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava",
        "@graknlabs_client_java//:client-java",
        "@graknlabs_graql//java:graql",
    ],
)